from .cambio import *
from .tube import *
from .pdf import *
from .git import *
from .torrent import *
from .google import *
from .magnets import *
from .proxy import *
from .xvideos import *
from .playstore import *
from .gag import *
from .xkcd import *
from .cotac import *
from .weather import *
from .time import *
from .giphy import *